name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: check
      run: cargo check
    - name: fmt
      run: cargo fmt -- --check
    - name: check
      run: cargo build
    - name: clippy
      run: |
        cargo clean -p iap
        cargo clippy
    - name: Run tests
      run: cargo test
